FROM apache/airflow:3.1.0


# Keep to install other packages that requires 'root' access
# USER root
# RUN apt-get update && apt-get install -y wget \
#    && pip install --upgrade pip\
#    && pip install --no-cache-dir pandas sqlalchemy psycopg2-binary pandas-stubs \
#    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER airflow
RUN pip install --no-cache-dir pandas requests openpyxl psycopg2-binary dbt-postgres


