
services:
  postgres_kestra:
    image: postgres
    container_name: postgres-kestra
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${KESTRA_DATABASE_NAME}
      POSTGRES_USER: ${KESTRA_USER}
      POSTGRES_PASSWORD: ${KESTRA_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  kestra:
    image: kestra/kestra:latest
    pull_policy: always
    container_name: kestra-server
    # Note that this setup with a root user is intended for development purpose.
    # Our base image runs without root, but the Docker Compose implementation needs root to access the Docker socket
    user: "${KESTRA_DOCKER_USER}"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
    env_file:
      - .env
    environment:
      # lines to expose Taxi DB credentials to flows
      ENV_TAXI_DB_USER: ${TAXI_DB_USER}
      ENV_TAXI_DB_PASSWORD: ${TAXI_DB_PASSWORD}
      ENV_TAXI_DATABASE_NAME: ${TAXI_DATABASE_NAME}
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres_kestra:5432/${KESTRA_DATABASE_NAME}
            driverClassName: org.postgresql.Driver
            username: ${KESTRA_USER}
            password: ${KESTRA_PASSWORD}
        kestra:
          # server:
          #   basicAuth:
          #     username: ${KESTRA_AUTH_USER} # it must be a valid email address
          #     password: ${KESTRA_AUTH_PASSWORD} # it must be at least 8 characters long with uppercase letter and a number
          repository:
            type: postgres
          storage:
            type: local
            local:
              basePath: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmpDir:
              path: /tmp/kestra-wd/tmp
          url: http://localhost:8080/
          env-vars-prefix: ENV_ 
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      postgres_kestra:
        condition: service_started

  # Taxi database  
  postgres_taxi_db:
    image: postgres
    container_name: postgres-taxi-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TAXI_DB_USER}
      POSTGRES_PASSWORD: ${TAXI_DB_PASSWORD}
      POSTGRES_DB: ${TAXI_DATABASE_NAME}
    volumes:
      - taxi-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    
# PgAdmin to manage both databases
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8085:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      postgres_taxi_db:
        condition: service_healthy

volumes:
  postgres-data:
    driver: local
  kestra-data: 
    driver: local
  taxi-data:
    driver: local
  pgadmin:
    driver: local
