services:
  pgdatabase:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - ./ny_tripdata_database:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - pg-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    networks:
      - pg-network
    depends_on:
      - pgdatabase

  ingestion:
    build: .
    container_name: ingest-script
    env_file:
      - .env
    depends_on:
      pgdatabase:
        condition: service_healthy
    networks:
      - pg-network
    volumes:
      - ./data:/app/data
      - ./logs:/logs

networks:
  pg-network:
    driver: bridge




