FROM python:3.13-slim

RUN apt-get update && apt-get install -y wget \
    && pip install --upgrade pip\
    && pip install --no-cache-dir pandas sqlalchemy psycopg2-binary pandas-stubs \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


WORKDIR /app
COPY . .


ENTRYPOINT ["python", "ingest-data.py"]

ENV PYTHONUNBUFFERED=1
